//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigOn.Infrastructure.Localize.Colors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColorsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigOn.Infrastructure.Localize.Colors.ColorsResource", typeof(ColorsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng kodu boş ola bilməz.
        /// </summary>
        public static string COLOR_HEXCODE_CANT_BE_EMPTY {
            get {
                return ResourceManager.GetString("COLOR_HEXCODE_CANT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng kodu mütləq göndərilməlidir.
        /// </summary>
        public static string COLOR_HEXCODE_CANT_BE_NULL {
            get {
                return ResourceManager.GetString("COLOR_HEXCODE_CANT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng kodu ən çox 7 simvolla qeyd edilməlidir.
        /// </summary>
        public static string COLOR_HEXCODE_MAX_CHARACTERS_7 {
            get {
                return ResourceManager.GetString("COLOR_HEXCODE_MAX_CHARACTERS_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng kodu ən az 7 simvolla qeyd edilməlidir.
        /// </summary>
        public static string COLOR_HEXCODE_MIN_CHARACTERS_7 {
            get {
                return ResourceManager.GetString("COLOR_HEXCODE_MIN_CHARACTERS_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng adı boş ola bilməz.
        /// </summary>
        public static string COLOR_NAME_CANT_BE_EMPTY {
            get {
                return ResourceManager.GetString("COLOR_NAME_CANT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng adı mütləq göndərilməlidir.
        /// </summary>
        public static string COLOR_NAME_CANT_BE_NULL {
            get {
                return ResourceManager.GetString("COLOR_NAME_CANT_BE_NULL", resourceCulture);
            }
        }
    }
}
